core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('', views.main, name="main"),
]

sepRSE/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


class User(AbstractUser):
    pass

core/views.py
from django.shortcuts import render

# Create your views here.


def main(request):
    return render(request, "core/main.html")

core/templates/core/main.html
{% extends 'base.html' %}

{% block content %}
    <h1>Hello SeptembRSE!</h1>
{% endblock %}

templates/base.html
{% spaceless %}
{% load static %}{% load i18n %}

<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/ico" href="{% static "images/favicon.ico" %}"/>
    <title>{% block title %}{% endblock title %}SeptembRSE Django</title>
    <link href="{% static 'custom.css' %}" rel="stylesheet" >
    <script src="{% static 'custom.js' %}"></script>
    <script src="https://kit.fontawesome.com/8a35fb449d.js" crossorigin="anonymous"></script>
    {% block extra_css %}{% endblock extra_css %}
  </head>
  <body>

    {% include 'snippets/base_menu.html' %}

    {% if messages %}
      <div class="container">
        {% for message in messages %}
          <div class="alert {{ message.tags }}">
            <p>{{ message }}</p>
          </div>
        {% endfor %}
      </div>
    {% endif %}

    <div class="container my-5">
      {% block content %}
      {% endblock content %}
    </div>

    <script src="{% static 'index.js' %}"></script>
    {% block extra_script %}{% endblock %}
  </body>
</html>
{% endspaceless %}

templates/base_clear.html
{% spaceless %}
{% load static %}{% load i18n %}

<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/ico" href="{% static "images/favicon.ico" %}"/>
    <title>{% block title %}{% endblock title %}FDP Workspace</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/8a35fb449d.js" crossorigin="anonymous"></script>
    {% block extra_css %}{% endblock extra_css %}
  </head>
  <body>

    <div class="container my-5">
      {% block content %}
      {% endblock content %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    {% block extra_script %}{% endblock %}
  </body>
</html>
{% endspaceless %}

templates/snippets/base_menu.html
<nav class="navbar navbar-expand-md navbar-light bg-light border-bottom">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url "core:main" %}">SeptembRSE Django</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link {% if request.path == '/' %} active {% endif %}" aria-current="page" href="{% url 'core:main'%}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if 'login' in request.path %} active {% endif %}" href="{% url "login" %}">Login</a>
        </li>
      </ul>
    </div>
  </div>
</nav>